---
- name: Remiをインストールする
  yum: 
    name={{ php.install.remi_url }}
    state=present

- name: phpをインストール
  yum: name={{ php.install.packages }} state=present enablerepo=remi,remi-php56

- name: phpのエラーレポーティングの設定を編集
  replace:
    dest=/etc/php.ini
    regexp="error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT"
    replace="error_reporting = {{ php.ini.error_reporting }}"
  notify: restart httpd

- name: phpのdisplay_errorsをon
  replace:
    dest=/etc/php.ini
    regexp="display_errors = Off"
    replace="display_errors = {{ php.ini.display_errors }}"
  notify: restart httpd

- name: phpのlog_errorをon
  replace:
    dest=/etc/php.ini
    regexp="log_errors = Off"
    replace="log_errors = {{ php.ini.log_errors }}"
  notify: restart httpd

- name: phpのlog_errorを
  replace:
    dest=/etc/php.ini
    regexp=";error_log = php_errors.log"
    replace="error_log = {{ php.ini.error_log_name }}"
  notify: restart httpd

- name: mbstring.languageをjapaneseに
  replace:
    dest=/etc/php.ini
    regexp=";mbstring.language = Japanese"
    replace="mbstring.language = {{ php.ini.mbstring.language }}"
  notify: restart httpd

- name: mbstring.languageをjapaneseに
  replace:
    dest=/etc/php.ini
    regexp=";mbstring.internal_encoding ="
    replace="mbstring.internal_encoding = {{ php.ini.mbstring.internal_encoding }}"
  notify: restart httpd

- name: mbstring.encoding_translation を明示的にOff
  replace:
    dest=/etc/php.ini
    regexp=";mbstring.encoding_translation = Off"
    replace="mbstring.encoding_translation = {{ php.ini.mbstring.encoding_translation }}"
  notify: restart httpd

- name: mbstring.http_inputを明示的にpass
  replace:
    dest=/etc/php.ini
    regexp=";mbstring.http_input ="
    replace="mbstring.http_input = {{ php.ini.mbstring.http_input }}"
  notify: restart httpd

- name: mbstring.http_outputを明示的にpass
  replace:
    dest=/etc/php.ini
    regexp=";mbstring.http_output ="
    replace="mbstring.http_output = {{ php.ini.mbstring.http_output }}"
  notify: restart httpd

- name: mbstring.detect_orderを明示的にpass
  replace:
    dest=/etc/php.ini
    regexp=";mbstring.detect_order = auto"
    replace="mbstring.detect_order = {{ php.ini.mbstring.detect_order }}"
  notify: restart httpd

- name: timezoneを設定
  replace:
    dest=/etc/php.ini
    regexp=";date.timezone ="
    replace="date.timezone = {{ php.ini.date.timezone }}"
  notify: restart httpd
